# deployment/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hatme-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hatme
  template:
    metadata:
      labels:
        app: hatme
    spec:
      containers:
      - name: hatme
        image: gcr.io/<your-project-id>/hatme:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            nvidia.com/gpu: 1  # Request one GPU per pod if available
---
apiVersion: v1
kind: Service
metadata:
  name: hatme-service
spec:
  selector:
    app: hatme
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
